### ISSUE TITLE
礼物api

### ISSUE THREAD

**Issue by dfaofeng** [lukaiqi/douyu-danmu#2]
get请求```https://gift.douyucdn.cn/japi/reward/giftv2/list/details/android/v1?giftPreInfo=v20003-99999```最后为房间号 前面的20003为礼物id,通过 get请求```https://www.douyu.com/betard/99999```返回的room.giftTempId 获得

**Comment by mengluo04** [comment]
> get请求`https://gift.douyucdn.cn/japi/reward/giftv2/list/details/android/v1?giftPreInfo=v20003-99999`最后为房间号 前面的20003为礼物id,通过 get请求`https://www.douyu.com/betard/99999`返回的room.giftTempId 获得

弹幕消息里的type为dbg只能获取到小礼物信息，spbc这个type貌似获取不到所在房间的飞机火箭等大礼物广播，不知道是否还有其他的type可以获取到大礼物信息
